version: '3'

services:
  web:
    build: .
    ports:
      - "8082:8082"
    volumes:
      # 使用環境變量來控制卷的類型
      - ${LOCAL_DEV_VOLUMES:-db_data}:/app/data
      - ${LOCAL_DEV_VOLUMES_CACHE:-cache_data}:/app/cache
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - WORKERS=2
      - TIMEOUT=120
      - MAX_REQUESTS=1000
      - MAX_REQUESTS_JITTER=50
      - DATABASE_DIR=/app/data
      - OAUTHLIB_INSECURE_TRANSPORT=1
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    command: >
      gunicorn --workers ${WORKERS:-2} --worker-class gevent --worker-connections 1000 --timeout ${TIMEOUT:-120} --max-requests ${MAX_REQUESTS:-1000} --max-requests-jitter ${MAX_REQUESTS_JITTER:-50} --bind 0.0.0.0:8082 --access-logfile - --error-logfile - app:app

volumes:
  db_data:
    driver: local
  cache_data:
    driver: local
