version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SECRET_KEY=your_secret_key_here
      # 可添加其他環境變數
    volumes:
      # 持久化數據
      - ./query_history.json:/app/query_history.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s